version: "3"
services:

  postgres:
    image: postgres:11.6
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - "./seed-db:/docker-entrypoint-initdb.d/"

  app:
    build: .
    depends_on:
      - postgres
    environment:
      DB_CONNECTION_STRING: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
      DEFAULT_COUNTRY_ID: gbr
    ports:
      - "5200:3000"
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules

  app-test:
    build: .
    depends_on:
      - postgres
    environment:
      DB_CONNECTION_STRING: postgres://user:pass@postgres:5432/db
      DEFAULT_COUNTRY_ID: gbr
    command: npm run test -- --watchAll
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
